const initialData = [
  { id: 1, title: "Classic Leather Wallet", price: 45, category: "Accessories" },
  { id: 2, title: "Wireless Bluetooth Earbuds", price: 89, category: "Electronics" },
  { id: 3, title: "Ceramic Coffee Mug", price: 15, category: "Home & Kitchen" },
  { id: 4, title: "Stainless Steel Water Bottle", price: 25, category: "Outdoors" },
  { id: 5, title: "Mechanical Keyboard", price: 120, category: "Electronics" },
  { id: 6, title: "Organic Cotton T-Shirt", price: 30, category: "Apparel" },
  { id: 7, title: "Yoga Mat (Non-Slip)", price: 55, category: "Fitness" },
  { id: 8, title: "Portable Power Bank", price: 40, category: "Electronics" },
  { id: 9, title: "Scented Soy Candle", price: 18, category: "Home & Decor" },
  { id: 10, title: "Leather Laptop Sleeve", price: 60, category: "Accessories" },
  { id: 11, title: "Bamboo Cutting Board", price: 22, category: "Home & Kitchen" },
  { id: 12, title: "Denim Jacket", price: 85, category: "Apparel" },
  { id: 13, title: "Smart LED Light Bulb", price: 15, category: "Electronics" },
  { id: 14, title: "Adjustable Dumbbells", price: 150, category: "Fitness" },
  { id: 15, title: "Canvas Backpack", price: 70, category: "Accessories" },
  { id: 16, title: "Glass Meal Prep Containers", price: 35, category: "Home & Kitchen" },
  { id: 17, title: "Polarized Sunglasses", price: 110, category: "Accessories" },
  { id: 18, title: "Noise-Cancelling Headphones", price: 299, category: "Electronics" },
  { id: 19, title: "Wool Throw Blanket", price: 45, category: "Home & Decor" },
  { id: 20, title: "Running Shoes", price: 125, category: "Fitness" },
  { id: 21, title: "Essential Oil Diffuser", price: 38, category: "Home & Decor" },
  { id: 22, title: "Cast Iron Skillet", price: 50, category: "Home & Kitchen" },
  { id: 23, title: "Minimalist Wall Clock", price: 32, category: "Home & Decor" },
  { id: 24, title: "Gaming Mouse", price: 65, category: "Electronics" },
  { id: 25, title: "Linen Bed Sheets", price: 140, category: "Home & Decor" },
  { id: 26, title: "Reusable Grocery Bags", price: 12, category: "Outdoors" },
  { id: 27, title: "Hiking Boots", price: 160, category: "Outdoors" },
  { id: 28, title: "Table Lamp", price: 45, category: "Home & Decor" },
  { id: 29, title: "Cordless Vacuum", price: 210, category: "Electronics" },
  { id: 30, title: "Electric Toothbrush", price: 95, category: "Personal Care" },
  { id: 31, title: "Bearded Grooming Kit", price: 40, category: "Personal Care" },
  { id: 32, title: "Hard Shell Suitcase", price: 180, category: "Travel" },
  { id: 33, title: "Travel Neck Pillow", price: 25, category: "Travel" },
  { id: 34, title: "Bluetooth Speaker", price: 75, category: "Electronics" },
  { id: 35, title: "Silicone Baking Mats", price: 20, category: "Home & Kitchen" },
  { id: 36, title: "Winter Parka", price: 250, category: "Apparel" },
  { id: 37, title: "Resistance Bands", price: 15, category: "Fitness" },
  { id: 38, title: "Leather Journal", price: 28, category: "Stationery" },
  { id: 39, title: "Fountain Pen", price: 45, category: "Stationery" },
  { id: 40, title: "Desk Organizer", price: 22, category: "Stationery" },
  { id: 41, title: "Air Purifier", price: 130, category: "Electronics" },
  { id: 42, title: "Electric Kettle", price: 40, category: "Home & Kitchen" },
  { id: 43, title: "Memory Foam Pillow", price: 55, category: "Home & Decor" },
  { id: 44, title: "UV Sanitizer Box", price: 60, category: "Electronics" },
  { id: 45, title: "Insulated Lunch Bag", price: 18, category: "Outdoors" },
  { id: 46, title: "Solar Power Lantern", price: 30, category: "Outdoors" },
  { id: 47, title: "Hoodie (Fleece)", price: 45, category: "Apparel" },
  { id: 48, title: "Cargo Pants", price: 55, category: "Apparel" },
  { id: 49, title: "Smartwatch", price: 199, category: "Electronics" },
  { id: 50, title: "Coffee Grinder", price: 80, category: "Home & Kitchen" }
];

export function getData(page=1,amount=10){
  if(page < 1) return initialData.slice( 1 , amount )
    return initialData.slice((page -1) * amount,(amount * page))
}
